name: location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_joystick: ^0.0.2
  flutter_map:
    hosted:
      name: flutter_map
      url: https://unpub.optyce.eu
    version: ^0.15.0
  flutter_map_location_marker:
    path: ../
  geolocator: any
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:

  uses-material-design: true
