name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 3.1.7
publish_to: https://unpub.optyce.eu

environment:
  sdk: ">=2.12.0 <=3.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_map:
    hosted:
      name: flutter_map
      url: https://unpub.optyce.eu
    version: ^0.15.1
  geolocator: ^8.2.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_joystick: ^0.0.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
